FROM lj996/node14-slim-yarn as build
COPY . /webapp
WORKDIR /webapp
RUN yarn --version
RUN node --version
RUN yarn
RUN yarn run build

FROM node:14.17.5-alpine3.14
COPY --from=build /webapp/dist /webapp/dist
COPY --from=build /webapp/server /webapp/server
WORKDIR /webapp
RUN node --version
RUN npm --version
RUN npm init -y
RUN npm i koa koa-static
EXPOSE 3000
ENTRYPOINT node ./server/server.ts