FROM lj996/node14-slim-yarn as build
COPY . /webapp
WORKDIR /webapp
RUN yarn --version
RUN node --version
RUN yarn
RUN yarn run build

FROM nginx:stable-alpine
COPY --from=build /webapp/dist /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]